version: "3"
services:
  postgres:
    image: postgres:$POSTGRES_VERSION
    restart: on-failure
    environment:
      POSTGRES_DB: subsocial
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 1986
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      backend:
        ipv4_address: 172.15.0.4

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTICSEARCH_VERSION
    restart: on-failure
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      MAX_MAP_COUNT: "64000"
      discovery.type: "single-node"
      cluster.name: "subsocial-cluster"
      node.name: "subsocial-node"
      network.host: "172.15.0.5"
      http.port: "9200"
      http.cors.enabled: "true"
      http.cors.allow-credentials: "true"
      http.cors.allow-origin: "172.15.0.2:3000"
      http.cors.allow-headers: "X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization,Access-Control-Allow-Headers,Accept"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      backend:
        ipv4_address: 172.15.0.5

  offchain:
    image: dappforce/subsocial-offchain:$OFFCHAIN_VERSION
    depends_on:
      - postgres
      - elasticsearch
    restart: on-failure
    environment:
      - NODE_ENV=production
      - SUBSTRATE_URL=$SUBSTRATE_URL
      - PGHOST=172.15.0.4
      - ES_NODE_URL=$ELASTIC_URL
    ports:
      - "3001:3001"
    networks:
      backend:
        ipv4_address: 172.15.0.3
