version: "3"
services:
  node_alice:
    image: dappforce/subsocial-node:$NODE_VERSION
    container_name: $CONT_NODE_ALICE
    restart: on-failure
    command: ./subsocial-node
      -d /data
      --chain=local
      --alice
      --ws-external
      --telemetry-url ws://telemetry.polkadot.io:1024
      --validator
      --pruning 'archive'
    volumes:
      - $VOLUME_LOCATION/chain_data/alice:/data
    ports:
      - "9944:9944"
    networks:
      backend:
        ipv4_address: 172.15.0.21

  node_bob:
    image: dappforce/subsocial-node:$NODE_VERSION
    container_name: $CONT_NODE_BOB
    restart: on-failure
    command: ./subsocial-node
      -d /data
      --chain=local
      --bob
      --port 30344
      --ws-port 9945
      --rpc-port 9935
      --telemetry-url ws://telemetry.polkadot.io:1024
      --validator
      --bootnodes '/ip4/172.15.0.21/tcp/30333/p2p/QmZ7cDTT4DAesod6gSqUup14dEfhHMyMcuhmfdzBAjqSCF'
    volumes:
      - $VOLUME_LOCATION/chain_data/bob:/data
    networks:
      backend:
        ipv4_address: 172.15.0.22
