version: "3"
services:
  node_alice:
    image: dappforce/subsocial-node:$NODE_VERSION
    restart: on-failure
    command: ./subsocial-node
      --chain=local
      --validator
      --alice
      -d /data
      --ws-external
    volumes:
      - $VOLUME_LOCATION/chain_data/alice:/data
    ports:
      - "9944:9944"
    networks:
      backend:
        ipv4_address: 172.15.0.21

  node_bob:
    image: dappforce/subsocial-node:$NODE_VERSION
    restart: on-failure
    command: ./subsocial-node
      --chain=local
      --validator
      --bob
      -d /data
      --port 30344
      --rpc-port 9935
      --ws-port 9945
      --bootnodes '/ip4/172.15.0.21/tcp/30333/p2p/QmZ7cDTT4DAesod6gSqUup14dEfhHMyMcuhmfdzBAjqSCF'
    volumes:
      - $VOLUME_LOCATION/chain_data/bob:/data
    networks:
      backend:
        ipv4_address: 172.15.0.22
