# docker-compose.yml
version: "3"
services:
  web-ui:
    image: dappforce/subsocial-ui:$WEBUI_VERSION
    restart: on-failure
    ports:
      - "3000:3000"
    networks:
      backend:
        ipv4_address: 172.15.0.2
